apiVersion: v1
kind: Pod
metadata:
  name: myapp-postgres
  labels:
    name: myapp-postgres
    app: demo-voting-app
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    ports:
      - containerPort: 5432
