apiVersion: v1
kind: Pod
metadata:
  name: redisapp-pod
  labels:
    name: redisapp-pod
    app: demo-voting-app
spec:
  containers:
  - name: redisapp-pod
    image: redis
    ports:
      - containerPort: 6379
