apiVersion: v1
kind: Service
metadata:
  name: voting
  labels:
    name: votingapp-service
    app: demo-voting-app

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: votingapp-pod
    app: demo-voting-app
    
