apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    app: demo-voting-app
spec:
  containers:
  - name: votingapp-pod
    image: kodekloud/examplevotingapp_vote:v1
    ports:
      - containerPort: 80
