apiVersion: v1
kind: Pod
metadata:
  name: worker-pod-app
  labels:
    name: worker-pod-app
    app: demo-voting-app
spec:
  containers:
    - name: worker-pod
      image: kodekloud/examplevotingapp_worker:v1