apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-rc
    type: fronted
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
  spec:
  containers:
  - name: nginx-container
    image: nginx
  
  replicas: 3